"""Type definitions for vega.

This module contains all Pydantic models, settings, and type definitions
for the vega module.

Generated by: madsci new module --template module/basic
Template version: 1.0.0
"""

from typing import Literal, Optional

from madsci.common.types.node_types import RestNodeConfig
from pydantic import BaseModel, Field


class VegaNodeConfig(RestNodeConfig):
    """Configuration for the Vega node.

    This class defines all configuration options for the node.
    Values can be set via environment variables, config files, or programmatically.
    """

    # Server configuration
    node_url: str = Field(
        default="http://localhost:2000/",
        description="URL where the node REST API is served",
    )

    # Interface configuration
    interface_type: Literal["real", "fake"] = Field(
        default="real",
        description="Which interface to use (real or fake)",
    )

    # Add your device-specific configuration here
    # device_address: str = Field(
    #     default="192.168.1.100",
    #     description="IP address or hostname of the device",
    # )
    # device_timeout: float = Field(
    #     default=30.0,
    #     description="Timeout for device operations in seconds",
    # )


class VegaInterfaceConfig(BaseModel):
    """Configuration for the Vega interface.

    This class defines settings specific to the hardware interface.
    """

    # Add your interface-specific configuration here
    # connection_timeout: float = Field(
    #     default=10.0,
    #     description="Timeout for establishing connection",
    # )
    # retry_count: int = Field(
    #     default=3,
    #     description="Number of retries for failed operations",
    # )
    pass


class VegaCommand(BaseModel):
    """Command to send to the vega device.

    Use this model to define the structure of commands sent to the device.
    """

    action: str = Field(description="Action to perform")
    parameters: dict = Field(
        default_factory=dict,
        description="Optional parameters for the action",
    )


class VegaResult(BaseModel):
    """Result from a vega device operation.

    Use this model to define the structure of results from device operations.
    """

    success: bool = Field(description="Whether the operation succeeded")
    data: Optional[dict] = Field(
        default=None,
        description="Result data from the operation",
    )
    error_message: Optional[str] = Field(
        default=None,
        description="Error message if operation failed",
    )
